services:
  postgres:
    container_name: postgres
    image: postgres
    restart: no
    environment:
      POSTGRES_DB: pet_family
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  seq:
    container_name: seq
    image: datalust/seq
    restart: no
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINPASSWORD: secure
    ports:
      - 5341:80
  minio:  
    image: minio/minio:latest  
    container_name: minio  
    restart: no 
    ports:
      - 9000:9000
      - 9001:9001
    volumes:  
      - minio-storage:/data  
      - minio-config:/root/.minio  
    command: server /data --console-address ":9001" 
volumes:
  postgres-data:
  minio-storage:
  minio-config:
  